spring.application.name=demo

spring.datasource.url=jdbc:h2:mem:telusko
spring.datasource.driverClassName=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#logging.level.org.springframework.boot.autoconfigure=DEBUG

spring.jpa.show-sql=true

spring.datasource.username=raj
spring.datasource.password=admin